### ISSUE TITLE
Linking stylesheet

### ISSUE THREAD

**Issue by aubreywullschleger** [TechChris/prj-rev-bwfs-dasmoto#1]
Important for errors!  Make sure you are using a relative file path to link your stylesheet in your HTML.  The `href` on line 6 should look like this:
`href="./resources/css/style.css"` 

https://github.com/TechChris/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L6

**Comment by TechChris** [comment]
Got it.
