### ISSUE TITLE
Using locally stored images

### ISSUE THREAD

**Issue by aubreywullschleger** [TechChris/prj-rev-bwfs-dasmoto#4]
Great! Nice work using locally stored images for your project. This is best practice for production code and helps your page load faster. 

Example: https://github.com/TechChris/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L11

Make sure to use descriptive `alt` attributes on all of your `<img>` elements like this: `<img src="resources/images/hacksaw.jpeg" alt="hacksaw paint brushes">` This is best practice and helps make your site more accessible!

Also, be sure to use a locally stored image as your `background-image` property for the `h1` selector in your CSS, like this:
`background-image: url("../images/pattern.jpeg");`

**Comment by TechChris** [comment]
Awesome, good to know; thank you. I purposely left one of the images being fetched from another url and made 3 pull from the resource folder because I wasn't sure which one is considered best practice. Thank you for clearing that up. Good tip about the alt tags, too.
