### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by aubreywullschleger** [TechChris/prj-rev-bwfs-dasmoto#6]
Grade: Meets expectations

Summary:
Wonderful job with this project! I love your easy to read HTML, your use of locally stored images, and your concise CSS.

A couple things to work on here: 1. linking your stylesheet with a relative file path, 2. using the `<strong>` element instead of the `<mark>` element, and 3. using descriptive `alt` attributes on your `<img>` elements.

Next, as a stretch goal, I challenge you to research and implement media queries to make your page responsive for all screen widths.  This is a challenge I think you are ready for based on your great work with this project!  Here are a couple resources to get you started: https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries and https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

**Comment by TechChris** [comment]
Cool - thanks!
